"""add dsl_anti_patterns table for few-shot self-healing"""

revision = '1c65d6ff37db'
down_revision = 'a36af804082f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsl_anti_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=False),
    sa.Column('wrong_snippet', sa.JSON(), nullable=False),
    sa.Column('context_note', sa.String(length=500), nullable=True),
    sa.Column('rule_violated', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_dsl_anti_patterns_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dsl_anti_patterns'))
    )
    op.create_index(op.f('ix_dsl_anti_patterns_created_at'), 'dsl_anti_patterns', ['created_at'], unique=False)
    op.create_index(op.f('ix_dsl_anti_patterns_error_category'), 'dsl_anti_patterns', ['error_category'], unique=False)
    op.create_index(op.f('ix_dsl_anti_patterns_project_id'), 'dsl_anti_patterns', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsl_anti_patterns_project_id'), table_name='dsl_anti_patterns')
    op.drop_index(op.f('ix_dsl_anti_patterns_error_category'), table_name='dsl_anti_patterns')
    op.drop_index(op.f('ix_dsl_anti_patterns_created_at'), table_name='dsl_anti_patterns')
    op.drop_table('dsl_anti_patterns')
    # ### end Alembic commands ###
