"""add_ai_planning_flow_steps"""

revision = 'a36af804082f'
down_revision = '25f18ab6cf2b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_planning_flow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('scenario_key', sa.String(length=100), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('expected_result', sa.String(length=1000), nullable=True),
    sa.Column('page_url', sa.String(length=1000), nullable=True),
    sa.Column('page_state', sa.String(length=10), nullable=True),
    sa.Column('element_indices', sa.JSON(), nullable=True),
    sa.Column('element_target_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_planning_sessions.id'], name=op.f('fk_ai_planning_flow_steps_session_id_ai_planning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_planning_flow_steps'))
    )
    op.create_index(op.f('ix_ai_planning_flow_steps_scenario_key'), 'ai_planning_flow_steps', ['scenario_key'], unique=False)
    op.create_index(op.f('ix_ai_planning_flow_steps_session_id'), 'ai_planning_flow_steps', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_planning_flow_steps_session_id'), table_name='ai_planning_flow_steps')
    op.drop_index(op.f('ix_ai_planning_flow_steps_scenario_key'), table_name='ai_planning_flow_steps')
    op.drop_table('ai_planning_flow_steps')
    # ### end Alembic commands ###
